# Dataset — AirBnb Paris
(1,12 GB, 5 file, 108 columns, 703 downloads, Updated 7 years ago)

https://www.kaggle.com/datasets/juliatb/airbnb-paris?select=reviews.csv

In [1]:
import pandas as pd
import numpy as np
import pyarrow
import json

# 1. Charger les données

### 1.1. Dataset "listings.csv"

In [2]:
#lire CSV_PATH
CSV_PATH = "df_airBnb_paris.csv"
df_listings = pd.read_csv(CSV_PATH, sep=',', encoding='utf-8', low_memory = False)

#Afficher 2 lignes et TOUTES les colonnes
pd.set_option("display.max_columns", None)
display(df_listings.head(3))

print("\n-------------------------------------")
print("Nombre de lignes et de colones")
print(df_listings.shape)

print("\n-------------------------------------")
print("Display info sur les colonnes et datatype")
display(df_listings.info())

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,2577,https://www.airbnb.com/rooms/2577,20181207151406,2018-12-08,Loft for 4 by Canal Saint Martin,"100 m2 loft (1100 sq feet) with high ceiling, ...",The district has any service or shop you may d...,"100 m2 loft (1100 sq feet) with high ceiling, ...",none,NaN,NaN,"Metro lines : 4, 8, 3, 11, 9.",NaN,NaN,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/09da057c-0...,NaN,2827,https://www.airbnb.com/users/show/2827,Karine,2008-09-09,"Casablanca, Grand Casablanca, Morocco","Arrivée à Casablanca il y a 4 ans, je suis amo...",within a day,75%,NaN,f,https://a0.muscache.com/im/pictures/17fe6c88-a...,https://a0.muscache.com/im/pictures/17fe6c88-a...,République,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Paris, Île-de-France, France",République,Entrepôt,NaN,Paris,Île-de-France,75010,Paris,"Paris, France",FR,France,48.869933,2.362511,t,Loft,Entire home/apt,4,2.0,2.0,2.0,Real Bed,"{TV,Internet,Wifi,Kitchen,Heating,Washer,Dryer...",NaN,$125.00,NaN,NaN,$0.00,$40.00,1,$0.00,3,1125,4 weeks ago,t,12,13,13,39,2018-12-08,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN,{PARIS},t,f,strict_14_with_grace_period,f,f,1,NaN
1,3109,https://www.airbnb.com/rooms/3109,20181207151406,2018-12-08,zen and calm,Appartement très calme de 50M2 Belle lumière D...,I bedroom appartment in Paris 14,I bedroom appartment in Paris 14,none,NaN,NaN,"ligne 13 and RER B, Ligne 4",NaN,yes I can help you out,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/baeae9e2-c...,NaN,3631,https://www.airbnb.com/users/show/3631,Anne,2008-10-14,"Paris, Île-de-France, France",NaN,within a day,100%,NaN,f,https://a0.muscache.com/im/users/3631/profile_...,https://a0.muscache.com/im/users/3631/profile_...,Alésia,1.0,1.0,"['email', 'phone', 'facebook', 'reviews']",t,f,"Paris, Île-de-France, France",Alésia,Observatoire,NaN,Paris,Île-de-France,75014,Paris,"Paris, France",FR,France,48.833494,2.318518,f,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{Internet,Wifi,Kitchen,""Paid parking off premi...",NaN,$75.00,$490.00,NaN,$0.00,$50.00,1,$0.00,3,15,5 days ago,t,3,4,17,271,2018-12-08,7,2016-12-27,2018-07-27,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,NaN,{PARIS},f,f,flexible,f,f,1,0.29
2,5396,https://www.airbnb.com/rooms/5396,20181207151406,2018-12-08,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","Small, well appointed studio apartment at the ...","Cozy, well-appointed and graciously designed s...",none,"You are within walking distance to the Louvre,...",The staircase leading up to the apartment is n...,The flat is close to two or t


-------------------------------------
Nombre de lignes et de colones
(59881, 96)

-------------------------------------
Display info sur les colonnes et datatype
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59881 entries, 0 to 59880
Data columns (total 96 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   id                                59881 non-null  int64  
 1   listing_url                       59881 non-null  object 
 2   scrape_id                         59881 non-null  int64  
 3   last_scraped                      59881 non-null  object 
 4   name                              59807 non-null  object 
 5   summary                           57524 non-null  object 
 6   space                             40516 non-null  object 
 7   description                       59384 non-null  object 
 8   experiences_offered               59881 non-null  object 
 9   neighborhood_overview         

None

# 2. Décrire les colonnes essentielles du dataset "listings.csv"

In [3]:
"""
Fonction générique : résumé des valeurs uniques par colonne. Pour chaque colonne :
- type (dtype)
- % de valeurs manquantes
- nombre de valeurs uniques
- aperçu des N premières valeurs unique
"""

def describe_unique_values(
    df: pd.DataFrame,
    max_unique_preview: int = 10,
    max_columns: int | None = None,
    include_object: bool = True,
    include_numeric: bool = True):
    """
    Affiche un résumé des valeurs uniques par colonne :
    - type de la colonne
    - pourcentage de valeurs manquantes
    - nombre de valeurs uniques
    - aperçu des premières valeurs uniques

    Paramètres
    ----------
    df : pd.DataFrame
        DataFrame à analyser
    max_unique_preview : int
        Nombre de valeurs uniques à afficher en aperçu
    max_columns : int | None
        Limiter le nombre de colonnes analysées (None = toutes)
    include_object : bool
        Inclure les colonnes de type object
    include_numeric : bool
        Inclure les colonnes numériques
    """

    cols = df.columns
    if max_columns:
        cols = cols[:max_columns]

    for col in cols:
        dtype = df[col].dtype

        if dtype == "object" and not include_object:
            continue
        if pd.api.types.is_numeric_dtype(dtype) and not include_numeric:
            continue

        total = len(df)
        missing = df[col].isna().sum()
        missing_pct = (missing / total) * 100
        unique_vals = df[col].dropna().unique()

        print("\n-------------------------------------")
        print(f"Colonne : {col}")
        print(f"Type : {dtype}")
        print(f"Valeurs manquantes : {missing_pct:.1f}%")
        print(f"Nombre de valeurs uniques : {len(unique_vals)}")
        print("-------------------------------------")

        display(unique_vals[:max_unique_preview])

#les colonnes object
describe_unique_values(df_listings)


-------------------------------------
Colonne : id
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------


array([ 2577,  3109,  5396,  7397,  7964,  8522,  9359,  9952, 10010,
       10270])


-------------------------------------
Colonne : listing_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------


array(['https://www.airbnb.com/rooms/2577',
       'https://www.airbnb.com/rooms/3109',
       'https://www.airbnb.com/rooms/5396',
       'https://www.airbnb.com/rooms/7397',
       'https://www.airbnb.com/rooms/7964',
       'https://www.airbnb.com/rooms/8522',
       'https://www.airbnb.com/rooms/9359',
       'https://www.airbnb.com/rooms/9952',
       'https://www.airbnb.com/rooms/10010',
       'https://www.airbnb.com/rooms/10270'], dtype=object)


-------------------------------------
Colonne : scrape_id
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------


array([20181207151406])


-------------------------------------
Colonne : last_scraped
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['2018-12-08', '2018-12-07'], dtype=object)


-------------------------------------
Colonne : name
Type : object
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 57244
-------------------------------------


array(['Loft for 4 by Canal Saint Martin', 'zen and calm',
       'Explore the heart of old Paris',
       'MARAIS - 2ROOMS APT - 2/4 PEOPLE',
       'Large & sunny flat with balcony !', 'GREAT FLAT w/ CITY VIEW',
       'Cozy, Central Paris: WALK or VELIB EVERYWHERE !',
       'Paris petit coin douillet', 'Paris view from my balcony - B&B',
       'Be charmed by real Paris 11th - B&B'], dtype=object)


-------------------------------------
Colonne : summary
Type : object
Valeurs manquantes : 3.9%
Nombre de valeurs uniques : 56199
-------------------------------------


array(['100 m2 loft (1100 sq feet) with high ceiling, open modern kitchen, cable tv, wifi, sleeping space up to 5 people, Republique area, 5 minutes from the St Martin Canal, Marais area, 10 min from Chatelet and the Louvre.',
       'Appartement très calme de 50M2 Belle lumière Draps et serviettes  Wifi',
       "Cozy, well-appointed and graciously designed studio apartment that mixes old and new aesthetics at the very heart of Paris, on the famous Isle St Louis that is a stone's throw from Le Marais, Quartier Latin, Notre Dame and Le Louvre. ",
       'VERY CONVENIENT, WITH THE BEST LOCATION !',
       'Very large & nice apartment all for you!  - Sunny living room & bedrooms - Well equiped and furnished - Central location & walking distance to many attractions - Great neighborhood',
       'Location! Location! Location! Just bring your toothbrush to this charmingly restored cheerful one bedroom in the center of the city. Exposed beams, facing an interior courtyard, walk to the wonder


-------------------------------------
Colonne : space
Type : object
Valeurs manquantes : 32.3%
Nombre de valeurs uniques : 39554
-------------------------------------


array(['The district has any service or shop you may desire at a walking distance, many restaurants and clubs as well.  I will be pleased to suggest our best addresses and give you directions to have a very enjoyable journey.  We have 1 separated bedroom and one mezzanine for the second bed. One bathroom is "en suite" to the main bedroom.  Welcome to our beautiful loft! Karine',
       'I bedroom appartment in Paris 14',
       'Small, well appointed studio apartment at the very heart of Paris, on the famous Isle St Louis. FOUR-NIGHT MINIMUM.  We are looking for quiet persons or couples to rent our fully equipped and furnished studio (about 30 square meters or 300 square feet) in central Paris on the famous Isle St. Louis. Please contact us for more information. Discounts available for longer stays. The location is superb. Pick up fresh bread at the nearby boulangerie and some exquisite cheese at the local fromagerie for breakfast. Take a late night stroll along the nearby Seine. Bar h


-------------------------------------
Colonne : description
Type : object
Valeurs manquantes : 0.8%
Nombre de valeurs uniques : 58583
-------------------------------------


array(['100 m2 loft (1100 sq feet) with high ceiling, open modern kitchen, cable tv, wifi, sleeping space up to 5 people, Republique area, 5 minutes from the St Martin Canal, Marais area, 10 min from Chatelet and the Louvre. The district has any service or shop you may desire at a walking distance, many restaurants and clubs as well.  I will be pleased to suggest our best addresses and give you directions to have a very enjoyable journey.  We have 1 separated bedroom and one mezzanine for the second bed. One bathroom is "en suite" to the main bedroom.  Welcome to our beautiful loft! Karine Metro lines : 4, 8, 3, 11, 9.',
       'I bedroom appartment in Paris 14',
       "Cozy, well-appointed and graciously designed studio apartment that mixes old and new aesthetics at the very heart of Paris, on the famous Isle St Louis that is a stone's throw from Le Marais, Quartier Latin, Notre Dame and Le Louvre. Small, well appointed studio apartment at the very heart of Paris, on the famous Isle 


-------------------------------------
Colonne : experiences_offered
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------


array(['none'], dtype=object)


-------------------------------------
Colonne : neighborhood_overview
Type : object
Valeurs manquantes : 40.5%
Nombre de valeurs uniques : 32885
-------------------------------------


array(['You are within walking distance to the Louvre, Notre Dame, Le Marais, Les Halles, Chatelet, St. Germain, Les Tuileries, le Jardin des Plantes, St. Michel, Sorbonne, Institut du Monde Arab, the Bastille and the Latin Quarter.  ',
       'This area typically Parisian, is nice, trendy and popular with, near the rue Oberkampf and its restaurants, bars, shops ... what to spend your evenings in the festive atmosphere. Also near the City Hall and the Marais district, the oldest district of Paris is also known for its "gay life". Still near the Canal Saint Martin now so characteristic of "Paris bobo" or you end up on Sunday for a picnic with friends, rollerblading or cycling ... Canal where you can also navigate a real curiosity The boulevard that stretches from the Place de la Bastille to the canal Saint Martin passing under your balcony gives oxygen and greenery with tall trees and colorful flower beds. It is also a lively area with the market very closeby (every Tuesday and Friday m


-------------------------------------
Colonne : notes
Type : object
Valeurs manquantes : 68.9%
Nombre de valeurs uniques : 16209
-------------------------------------


array(['The staircase leading up to the apartment is narrow and old -- this is a very old building, so perhaps unsuitable for those with difficulty walking or climbing up stairs.',
       'Important: Be conscious that an apartment in a building of the old Paris is not an apartment in a tower of Singapore... If you do not, please do not make a request! I rent easily this place and I prefer to welcome open minded guests!',
       'Velib station outside.',
       "We participated in the very beginning of the Airbnb'adventure  in Paris in 2009 and I had the pleasure to spend a day with Joe, one of the founders, who photographed the apartment by himself. I doubt he does that again today !!! I keep a very pleasant memory of this day and I am admiring the way traveled by Airbnb with whom I hope to continue a long way.",
       "Important remarks / Remarques importantes    When rented, the flat can accomodate for up to six guests, which is no small amount for a 65 m2 flat. My purpose is to hel


-------------------------------------
Colonne : transit
Type : object
Valeurs manquantes : 36.3%
Nombre de valeurs uniques : 36492
-------------------------------------


array(['Metro lines : 4, 8, 3, 11, 9.', 'ligne 13 and RER B, Ligne 4',
       "The flat is close to two or three major metro lines, as well near several of Paris' Velibre stations where you can rent a bike for a small fee.",
       'Metro station HÖTEL-DE-VILLE is 100 meters close.',
       'All the major metros and RERs are at Les Halles or Chatelet. Very easy to arrive and the night buses are also nearby at Hotel de Ville, 5 minutes away walking. Velib in front of building!',
       'I can also organize transport service.Easy access from the train stations and airports. I am in contact with you as soon as your booking is made and I provide you with accurate information access to the apartment. One minute to metro station Saint Ambroise line 9 makes traveling by metro very easy. Many connections with the main axes RER, SNCF, Airports ... Taxi and Bus Station nearby. Bike rental, the Vélibs so pleasant  ...',
       'Easy access from the train stations and airports. I am in contact wit


-------------------------------------
Colonne : access
Type : object
Valeurs manquantes : 51.8%
Nombre de valeurs uniques : 22648
-------------------------------------


array(["The flat includes its own modern bathroom, a washing machine, stove, oven, toaster and coffee press. For sleeping there is only a fold-out couch but it has a real mattress that's rather comfortable. There is a desk that's excellent for working, bar stools, a fully-equipped kitchenette, television, closet space, wireless broadband internet, towels, linens, pots, pans, plates, forks, knives.  All you need to bring are your clothes and toothbrush. Excellent for visiting scholars, businesspersons or tourists. Absolutely no pets or smoking allowed.  ",
       'You have access to all the apartment.',
       "You are alone in the flat, the entire city is at your feet. You will enjoy being able to go outside and be astonished at the liveliness of the area and then come back home and it's facing two courtyards so there is a calm which helps make being in the center attractive.",
       'Cet appartement n est pas accessible aux Handicapés.. logement ancien et petit...',
       'Services 


-------------------------------------
Colonne : interaction
Type : object
Valeurs manquantes : 52.6%
Nombre de valeurs uniques : 24322
-------------------------------------


array(['yes I can help you out',
       'We expect guests to operate rather independently, though we welcome questions about the flat and urge you to call us immediately if there is any kind of emergency or trouble.',
       'We are there to welcome you, give you keys and advice you on great places to eat & drink around.',
       "I am available 18 hours a day by text, have lots of friends (and friendly neighbors) in Paris available to help answer any questions. It's easy to rent with me. Like having your family flat for your personal use!",
       'I welcome you personally on your arrival, I give you all the useful information to make the most of the apartment and its facilities and I give you the services and shops of the neighborhood. Throughout your stay you can ask me because I live next door.',
       'I welcome you personally upon arrival, I give you all the information to get the most of the apartment and its facilities and I tell you the services and boutiques in the area. All


-------------------------------------
Colonne : house_rules
Type : object
Valeurs manquantes : 52.4%
Nombre de valeurs uniques : 23463
-------------------------------------


array(['This is a small flat in a very old building that we also use when the two of us and our infant daughter come to Paris. We ask that you treat the flat as if it were your own place, and leave it reasonably tidy when you leave. No smoking or pets. Please remember to double lock the door when you step out.',
       "ELECTRICITY INCLUDED FOR NORMAL USING. PLEASE TURN OFF LIGHTS AND HEATING EACH TME YOU LEAVE IMPORTANT FOR TRASH : RESPECT THE SELECTIVE SORTING !  AND DON'T BE NOISY IN THE STAIRS WITH BAGS !",
       'Respect.',
       'This residence is limited to TWO people and is for a MINIMUM rental of SIX MONTHS.',
       'DO NOT USE FIREPLACE',
       'You are feeling free in your home away from home.  The occupation of the apartment must be respecting the neighbors.  Information to become familiar with the apartment and its surroundings will be given on arrival. We are closeby for the duration of your stay to assist you if necessary. We are happy to help you if you need assista


-------------------------------------
Colonne : thumbnail_url
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------


array([], dtype=float64)


-------------------------------------
Colonne : medium_url
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------


array([], dtype=float64)


-------------------------------------
Colonne : picture_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59680
-------------------------------------


array(['https://a0.muscache.com/im/pictures/09da057c-0120-4d5c-b464-d95c75921dde.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/baeae9e2-cd53-4ac3-b1bc-4055c0bb2e77.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/52413/f9bf76f5_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/67928287/330bd78c_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/4471349/6fb3de47_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/30560/08769a1a_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/c2965945-061f-4ad8-a547-d617e5781827.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/52474/aeb7de2a_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/1d8c4fb5-ac66-4140-871a-0f558fb9f280.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/86310660/d86f0c24_original.jpg?aki_policy=large'],
      dtype=object)


-------------------------------------
Colonne : xl_picture_url
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------


array([], dtype=float64)


-------------------------------------
Colonne : host_id
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51336
-------------------------------------


array([ 2827,  3631,  7903,  2626, 22155, 25435, 28422, 33534, 33995,
       37107])


-------------------------------------
Colonne : host_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51336
-------------------------------------


array(['https://www.airbnb.com/users/show/2827',
       'https://www.airbnb.com/users/show/3631',
       'https://www.airbnb.com/users/show/7903',
       'https://www.airbnb.com/users/show/2626',
       'https://www.airbnb.com/users/show/22155',
       'https://www.airbnb.com/users/show/25435',
       'https://www.airbnb.com/users/show/28422',
       'https://www.airbnb.com/users/show/33534',
       'https://www.airbnb.com/users/show/33995',
       'https://www.airbnb.com/users/show/37107'], dtype=object)


-------------------------------------
Colonne : host_name
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 10038
-------------------------------------


array(['Karine', 'Anne', 'Borzou', 'Franck', 'Anaïs', 'Adrien',
       'Bernadette', 'Elisabeth', 'Pascal', 'Michael'], dtype=object)


-------------------------------------
Colonne : host_since
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 3140
-------------------------------------


array(['2008-09-09', '2008-10-14', '2009-02-14', '2008-08-30',
       '2009-06-18', '2009-07-13', '2009-07-29', '2009-08-24',
       '2009-08-26', '2009-09-08'], dtype=object)


-------------------------------------
Colonne : host_location
Type : object
Valeurs manquantes : 0.3%
Nombre de valeurs uniques : 2097
-------------------------------------


array(['Casablanca, Grand Casablanca, Morocco',
       'Paris, Île-de-France, France', 'Istanbul, İstanbul, Turkey',
       'Paris, Ile-de-France, France',
       'New York, New York, United States', 'France', 'Vietnam',
       'Paris and venice Beach', 'Longjumeau, Ile-de-France, France',
       'Madrid, Community of Madrid, Spain'], dtype=object)


-------------------------------------
Colonne : host_about
Type : object
Valeurs manquantes : 49.3%
Nombre de valeurs uniques : 24075
-------------------------------------


array(["Arrivée à Casablanca il y a 4 ans, je suis amoureuse de cette ville méconnue des visiteurs hors voyage d'affaire. ",
       "We are both journalists based in the Middle East, and spend a lot of time traveling for work, so we understand what people need when they're away from home. Delphine is Parisian -- her aunt helps us rent out the apartment. We both love Paris and try to make it easy for people to come and visit the city. ",
       'I am a writer,51, author of novels, books of linguistics...',
       'Hello ! \r\nOur apartment is great and I am sure you will love it ! I will be happy to share with you tips and my favourites places to make your stay super nice.',
       'De Paris, propre et organisé.',
       'I am a Native New Yorker (yes, I was born and raised here!) and have lived in Boston, Paris and Los Angeles and speak a bit of French and Spanish and about two words of Italian. I work in the legal field. I went to culinary school to study pastry many years ago and now


-------------------------------------
Colonne : host_response_time
Type : object
Valeurs manquantes : 48.3%
Nombre de valeurs uniques : 4
-------------------------------------


array(['within a day', 'within an hour', 'within a few hours',
       'a few days or more'], dtype=object)


-------------------------------------
Colonne : host_response_rate
Type : object
Valeurs manquantes : 48.3%
Nombre de valeurs uniques : 75
-------------------------------------


array(['75%', '100%', '86%', '80%', '90%', '50%', '0%', '97%', '74%',
       '63%'], dtype=object)


-------------------------------------
Colonne : host_acceptance_rate
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------


array([], dtype=float64)


-------------------------------------
Colonne : host_is_superhost
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['f', 't'], dtype=object)


-------------------------------------
Colonne : host_thumbnail_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51164
-------------------------------------


array(['https://a0.muscache.com/im/pictures/17fe6c88-a480-4a63-bfa7-1c0951105958.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/3631/profile_pic/1375800198/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/7903/profile_pic/1280002723/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/pictures/58f00c4d-f805-4605-9f7c-5c848814c828.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/22155/profile_pic/1271497205/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/25435/profile_pic/1259111394/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/28422/profile_pic/1319547089/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/pictures/user/4f775bb4-9080-4943-aa57-d516708aec81.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/33995/profile_pic/1392889357/original.jpg?aki_policy=profile_small',
 


-------------------------------------
Colonne : host_picture_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51164
-------------------------------------


array(['https://a0.muscache.com/im/pictures/17fe6c88-a480-4a63-bfa7-1c0951105958.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/3631/profile_pic/1375800198/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/7903/profile_pic/1280002723/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/pictures/58f00c4d-f805-4605-9f7c-5c848814c828.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/22155/profile_pic/1271497205/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/25435/profile_pic/1259111394/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/28422/profile_pic/1319547089/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/pictures/user/4f775bb4-9080-4943-aa57-d516708aec81.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/33995/profile_pic/1392889357/original.jpg?aki_


-------------------------------------
Colonne : host_neighbourhood
Type : object
Valeurs manquantes : 14.4%
Nombre de valeurs uniques : 247
-------------------------------------


array(['République', 'Alésia', 'Saint-Paul - Ile Saint-Louis',
       'Le Marais', "Gare du Nord - Gare de I'Est",
       'Père Lachaise - Ménilmontant',
       'Châtelet - Les Halles - Beaubourg', 'Montmartre', 'Saint-Lazare',
       'Panthéon'], dtype=object)


-------------------------------------
Colonne : host_listings_count
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 83
-------------------------------------


array([ 2.,  1.,  3.,  6.,  4., 14.,  7., 83.,  5., 54.])


-------------------------------------
Colonne : host_total_listings_count
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 83
-------------------------------------


array([ 2.,  1.,  3.,  6.,  4., 14.,  7., 83.,  5., 54.])


-------------------------------------
Colonne : host_verifications
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 451
-------------------------------------


array(["['email', 'phone', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'facebook', 'reviews']",
       "['email', 'phone', 'facebook', 'google', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']",
       "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'government_id']",
       "['email', 'phone', 'reviews']",
       "['email', 'phone', 'manual_online', 'facebook', 'reviews', 'manual_offline', 'jumio', 'offline_government_id', 'selfie', 'government_id', 'identity_manual', 'work_email']",
       "['email', 'phone', 'facebook', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'reviews', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']",
       "['email', 'phone']"], dtype=object)


-------------------------------------
Colonne : host_has_profile_pic
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Colonne : host_identity_verified
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Colonne : street
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 242
-------------------------------------


array(['Paris, Île-de-France, France', 'Paris, Ile-de-France, France',
       'Paris, IDF, France', 'Paris, France', 'Paris, IdF, France',
       'Paris, 4th arrondissement, Île-de-France, France',
       'Saint-Mandé, Île-de-France, France', 'Paris, Paris, France',
       'Paris , Île-de-France, France',
       'Paris-13E-Arrondissement, Île-de-France, France'], dtype=object)


-------------------------------------
Colonne : neighbourhood
Type : object
Valeurs manquantes : 4.4%
Nombre de valeurs uniques : 61
-------------------------------------


array(['République', 'Alésia', 'Saint-Paul - Ile Saint-Louis',
       'Le Marais', "Gare du Nord - Gare de I'Est",
       'Père Lachaise - Ménilmontant', 'Montmartre', 'Saint-Lazare',
       'Panthéon', "Place d'Italie - Quartier Chinois"], dtype=object)


-------------------------------------
Colonne : neighbourhood_cleansed
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 20
-------------------------------------


array(['Entrepôt', 'Observatoire', 'Hôtel-de-Ville', 'Opéra',
       'Ménilmontant', 'Louvre', 'Popincourt', 'Buttes-Montmartre',
       'Élysée', 'Panthéon'], dtype=object)


-------------------------------------
Colonne : neighbourhood_group_cleansed
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------


array([], dtype=float64)


-------------------------------------
Colonne : city
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 132
-------------------------------------


array(['Paris', 'Paris, 4th arrondissement', 'Saint-Mandé', 'Paris ',
       'Paris-13E-Arrondissement', 'Levallois-Perret',
       'Paris-2E-Arrondissement', 'Paris 4e arrondissement', 'Vincennes',
       'Boulogne-Billancourt'], dtype=object)


-------------------------------------
Colonne : state
Type : object
Valeurs manquantes : 1.2%
Nombre de valeurs uniques : 50
-------------------------------------


array(['Île-de-France', 'Ile-de-France', 'IDF', 'IdF', 'Paris', 'FRANCE',
       'France', 'Ile de France', 'Pairs', 'Ile de france'], dtype=object)


-------------------------------------
Colonne : zipcode
Type : object
Valeurs manquantes : 1.3%
Nombre de valeurs uniques : 75
-------------------------------------


array(['75010', '75014', '75004', '75009', '75020', '75001', '75011',
       '75018', '75008', '75005'], dtype=object)


-------------------------------------
Colonne : market
Type : object
Valeurs manquantes : 0.2%
Nombre de valeurs uniques : 22
-------------------------------------


array(['Paris', 'Other (International)', 'Loire Valley', 'Toulouse',
       'Orleans', 'Marseille', 'Basque Country', 'Deauville', 'Brussels',
       'Berlin'], dtype=object)


-------------------------------------
Colonne : smart_location
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 134
-------------------------------------


array(['Paris, France', 'Paris, 4th arrondissement, France',
       'Saint-Mandé, France', 'Paris , France',
       'Paris-13E-Arrondissement, France', 'Levallois-Perret, France',
       'Paris-2E-Arrondissement, France',
       'Paris 4e arrondissement, France', 'FR, France',
       'Vincennes, France'], dtype=object)


-------------------------------------
Colonne : country_code
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['FR', 'CH'], dtype=object)


-------------------------------------
Colonne : country
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['France', 'Switzerland'], dtype=object)


-------------------------------------
Colonne : latitude
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------


array([48.86993262, 48.83349369, 48.85100067, 48.85757577, 48.87464191,
       48.86527873, 48.85898545, 48.86226582, 48.86277521, 48.86743024])


-------------------------------------
Colonne : longitude
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------


array([2.36251064, 2.31851792, 2.35869042, 2.35275131, 2.34341111,
       2.39326349, 2.34734722, 2.37134096, 2.37467959, 2.37523953])


-------------------------------------
Colonne : is_location_exact
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Colonne : property_type
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 32
-------------------------------------


array(['Loft', 'Apartment', 'Condominium', 'Bed and breakfast', 'House',
       'Townhouse', 'Guesthouse', 'Boat', 'Guest suite', 'Tiny house'],
      dtype=object)


-------------------------------------
Colonne : room_type
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 3
-------------------------------------


array(['Entire home/apt', 'Private room', 'Shared room'], dtype=object)


-------------------------------------
Colonne : accommodates
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 17
-------------------------------------


array([ 4,  2,  3,  5,  6,  1, 14,  9,  7,  8])


-------------------------------------
Colonne : bathrooms
Type : float64
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 18
-------------------------------------


array([2. , 1. , 1.5, 2.5, 4.5, 0.5, 0. , 3. , 4. , 5. ])


-------------------------------------
Colonne : bedrooms
Type : float64
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 10
-------------------------------------


array([ 2.,  1.,  0.,  3.,  5.,  4.,  6.,  7., 10., 50.])


-------------------------------------
Colonne : beds
Type : float64
Valeurs manquantes : 0.4%
Nombre de valeurs uniques : 19
-------------------------------------


array([ 2.,  1.,  3.,  4.,  0.,  8.,  6.,  5.,  7., 10.])


-------------------------------------
Colonne : bed_type
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 5
-------------------------------------


array(['Real Bed', 'Pull-out Sofa', 'Futon', 'Couch', 'Airbed'],
      dtype=object)


-------------------------------------
Colonne : amenities
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 53706
-------------------------------------


array(['{TV,Internet,Wifi,Kitchen,Heating,Washer,Dryer,Essentials,Hangers,Iron,"Laptop friendly workspace","Hot water","Host greets you"}',
       '{Internet,Wifi,Kitchen,"Paid parking off premises","Family/kid friendly",Washer,"Smoke detector",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Self check-in","Smart lock","Children’s books and toys","Hot water","Luggage dropoff allowed"}',
       '{TV,"Cable TV",Internet,Wifi,Kitchen,Heating,Washer,"Smoke detector","Fire extinguisher",Essentials,Shampoo,Hangers,"Hair dryer","Laptop friendly workspace","Hot water","Bed linens","Extra pillows and blankets","Long term stays allowed","Host greets you"}',
       '{TV,"Cable TV",Internet,Wifi,Kitchen,"Paid parking off premises","Buzzer/wireless intercom",Heating,"Family/kid friendly",Washer,"Smoke detector","Carbon monoxide detector",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Hot water","Host greets you"}',
       '{TV,"Cable TV",Internet


-------------------------------------
Colonne : square_feet
Type : float64
Valeurs manquantes : 97.7%
Nombre de valeurs uniques : 142
-------------------------------------


array([  0., 350., 538., 377., 603., 248., 269., 484., 560., 323.])


-------------------------------------
Colonne : price
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 587
-------------------------------------


array(['$125.00', '$75.00', '$115.00', '$99.00', '$90.00', '$70.00',
       '$135.00', '$105.00', '$80.00', '$85.00'], dtype=object)


-------------------------------------
Colonne : weekly_price
Type : object
Valeurs manquantes : 79.7%
Nombre de valeurs uniques : 769
-------------------------------------


array(['$490.00', '$600.00', '$770.00', '$560.00', '$475.00', '$425.00',
       '$539.00', '$934.00', '$900.00', '$400.00'], dtype=object)


-------------------------------------
Colonne : monthly_price
Type : object
Valeurs manquantes : 87.0%
Nombre de valeurs uniques : 839
-------------------------------------


array(['$2,000.00', '$2,200.00', '$1,480.00', '$1,300.00', '$1,000.00',
       '$1,510.00', '$3,297.00', '$3,000.00', '$2,300.00', '$1,500.00'],
      dtype=object)


-------------------------------------
Colonne : security_deposit
Type : object
Valeurs manquantes : 31.8%
Nombre de valeurs uniques : 421
-------------------------------------


array(['$0.00', '$200.00', '$500.00', '$1,500.00', '$250.00', '$400.00',
       '$800.00', '$600.00', '$1,000.00', '$80.00'], dtype=object)


-------------------------------------
Colonne : cleaning_fee
Type : object
Valeurs manquantes : 28.0%
Nombre de valeurs uniques : 184
-------------------------------------


array(['$40.00', '$50.00', '$36.00', '$60.00', '$200.00', '$20.00',
       '$35.00', '$70.00', '$25.00', '$0.00'], dtype=object)


-------------------------------------
Colonne : guests_included
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 15
-------------------------------------


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


-------------------------------------
Colonne : extra_people
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 101
-------------------------------------


array(['$0.00', '$10.00', '$45.00', '$30.00', '$4.00', '$3.00', '$13.00',
       '$29.00', '$5.00', '$25.00'], dtype=object)


-------------------------------------
Colonne : minimum_nights
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 102
-------------------------------------


array([  3,   2,  10, 180,   5,  90,  30,   1,   7,   6])


-------------------------------------
Colonne : maximum_nights
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 257
-------------------------------------


array([1125,   15,   30,   23,  365,  119,   60,  730,   90,   20])


-------------------------------------
Colonne : calendar_updated
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 77
-------------------------------------


array(['4 weeks ago', '5 days ago', '6 days ago', 'today', '2 days ago',
       '10 months ago', '3 weeks ago', 'yesterday', '7 weeks ago',
       '2 months ago'], dtype=object)


-------------------------------------
Colonne : has_availability
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------


array(['t'], dtype=object)


-------------------------------------
Colonne : availability_30
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 31
-------------------------------------


array([12,  3,  1,  4,  0,  2,  6, 11,  8,  5])


-------------------------------------
Colonne : availability_60
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 61
-------------------------------------


array([13,  4,  6, 33, 30,  0, 26, 15, 41,  3])


-------------------------------------
Colonne : availability_90
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 91
-------------------------------------


array([13, 17, 28, 49,  4, 60,  7, 11, 51, 39])


-------------------------------------
Colonne : availability_365
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 366
-------------------------------------


array([ 39, 271, 113, 286, 164, 335, 282, 219,  61,  63])


-------------------------------------
Colonne : calendar_last_scraped
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['2018-12-08', '2018-12-07'], dtype=object)


-------------------------------------
Colonne : number_of_reviews
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 378
-------------------------------------


array([  0,   7, 148, 231,   6,   1,  17, 144, 147,  41])


-------------------------------------
Colonne : first_review
Type : object
Valeurs manquantes : 20.9%
Nombre de valeurs uniques : 2620
-------------------------------------


array(['2016-12-27', '2009-06-30', '2011-04-08', '2010-05-10',
       '2010-06-16', '2013-03-19', '2010-01-11', '2010-09-02',
       '2009-12-20', '2011-03-13'], dtype=object)


-------------------------------------
Colonne : last_review
Type : object
Valeurs manquantes : 20.9%
Nombre de valeurs uniques : 1655
-------------------------------------


array(['2018-07-27', '2018-11-21', '2018-11-19', '2015-09-14',
       '2010-06-16', '2018-12-01', '2018-11-23', '2018-11-25',
       '2016-10-02', '2016-10-01'], dtype=object)


-------------------------------------
Colonne : review_scores_rating
Type : float64
Valeurs manquantes : 22.7%
Nombre de valeurs uniques : 52
-------------------------------------


array([100.,  94.,  96.,  99.,  97.,  88.,  93.,  92.,  95.,  98.])


-------------------------------------
Colonne : review_scores_accuracy
Type : float64
Valeurs manquantes : 22.8%
Nombre de valeurs uniques : 9
-------------------------------------


array([10.,  9.,  8.,  7.,  6.,  2.,  5.,  4.,  3.])


-------------------------------------
Colonne : review_scores_cleanliness
Type : float64
Valeurs manquantes : 22.8%
Nombre de valeurs uniques : 9
-------------------------------------


array([10.,  9.,  8.,  6.,  7.,  4.,  2.,  5.,  3.])


-------------------------------------
Colonne : review_scores_checkin
Type : float64
Valeurs manquantes : 22.9%
Nombre de valeurs uniques : 9
-------------------------------------


array([10.,  9.,  8.,  6.,  7.,  5.,  2.,  4.,  3.])


-------------------------------------
Colonne : review_scores_communication
Type : float64
Valeurs manquantes : 22.8%
Nombre de valeurs uniques : 9
-------------------------------------


array([10.,  9.,  8.,  2.,  6.,  7.,  4.,  5.,  3.])


-------------------------------------
Colonne : review_scores_location
Type : float64
Valeurs manquantes : 22.9%
Nombre de valeurs uniques : 9
-------------------------------------


array([10.,  9.,  8.,  6.,  4.,  7.,  5.,  2.,  3.])


-------------------------------------
Colonne : review_scores_value
Type : float64
Valeurs manquantes : 22.9%
Nombre de valeurs uniques : 9
-------------------------------------


array([10.,  9.,  8.,  6.,  7.,  2.,  4.,  5.,  3.])


-------------------------------------
Colonne : requires_license
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Colonne : license
Type : object
Valeurs manquantes : 75.7%
Nombre de valeurs uniques : 13914
-------------------------------------


array(['7510400829623', '5962', '7510500148022', '7511111100537044',
       '7511801401834', '7511300241931', '7511100262771', '7511102600669',
       '7511802269686', '7510102359633'], dtype=object)


-------------------------------------
Colonne : jurisdiction_names
Type : object
Valeurs manquantes : 1.3%
Nombre de valeurs uniques : 31
-------------------------------------


array(['{PARIS}', '{Paris}', '{"LEVALLOIS PERRET"}', '{VINCENNES}',
       '{"BOULOGNE BILLANCOURT"}', '{PANTIN}', '{"BRAS PANON"}',
       '{"LE KREMLIN BICETRE"}', '{"NEUILLY SUR SEINE"}',
       '{"ISSY LES MOULINEAUX"}'], dtype=object)


-------------------------------------
Colonne : instant_bookable
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Colonne : is_business_travel_ready
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------


array(['f'], dtype=object)


-------------------------------------
Colonne : cancellation_policy
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 6
-------------------------------------


array(['strict_14_with_grace_period', 'flexible', 'moderate',
       'super_strict_30', 'strict', 'super_strict_60'], dtype=object)


-------------------------------------
Colonne : require_guest_profile_picture
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['f', 't'], dtype=object)


-------------------------------------
Colonne : require_guest_phone_verification
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------


array(['f', 't'], dtype=object)


-------------------------------------
Colonne : calculated_host_listings_count
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 57
-------------------------------------


array([ 1,  6,  3,  2,  4,  7, 72,  5, 13, 39])


-------------------------------------
Colonne : reviews_per_month
Type : float64
Valeurs manquantes : 20.9%
Nombre de valeurs uniques : 885
-------------------------------------


array([0.29, 1.29, 2.47, 0.06, 0.01, 0.24, 1.33, 1.46, 0.38, 0.17])

# 3. Les colonnes à prendre ou à laisser

### Les colonnes à garder absolument et transformer en cas de besoin :

- Identité & localisation (cartographie, clustering, matching géospatial, itinéraires) : latitude (0% missing), longitude (0% missing), name (0,1% missing), city (0,1% missing), zipcode (1% missing), transit (36% missing), listing_url (0.01% missing)

- Type de logement & capacité : description (1% missing), property_type (0% missing), bedrooms (0.11% missing), beds (% missing), bed_type (0% missing), bathrooms (0.13% missing), accommodates (ex : accommodates=2 --> logement pour 2 personnes) (0% missing), amenities (0% missing)

- Prix : price (0% missing), cleaning_fee (27% missing), guests_included (0% missing), extra_people (0% missing)

- Règles : security_deposit (31% missing), minimum_nights (0% missing), maximum_nights (0% missing), cancellation_policy (0% missing), require_guest_profile_picture (0% missing), require_guest_phone_verification (0% missing), 

- Disponibilité : availability_30 (ex : availability_30 = 12 → 12 nuits libres sur les 30 à venir) (0% missing), availability_60 (0% missing), availability_90 (0% missing), availability_365 (0% missing)

- Avis & réputation (score) : number_of_reviews (0% missing), review_scores_rating (23% missing), reviews_per_month (21% missing), last_review (21% missing), review_scores_location (23% missing), review_scores_cleanliness (23% missing), review_scores_value (23% missing),

### Les colonnes à ignorer :

neighborhood_overview (40% missing), space (32% missing), notes (69% missing), interaction (52% missing), summary (4% missing), house_rules (52% missing), access (52% missing), host_url (0% missing), host_name (0,01% missing), host_identity_verified (0,01% missing), host_about (49% missing), host_since (0,01% missing), host_is_superhost (0,01% missing), room_type (0% missing),host_response_time (48% missing), 

host_verifications (0,01% missing), host_response_rate (48% missing), first_review (21% missing), review_scores_checkin (23% missing), review_scores_accuracy (23% missing), review_scores_communication (23% missing), calendar_updated (0% missing), has_availability (0% missing), is_location_exact (0% missing), street (0% missing), country (0% missing), country_code (0% missing), neighbourhood_cleansed (0% missing), host_id (0% missing), host_listings_count (0.01% missing), host_total_listings_count (0.01% missing), picture_url (0% missing), smart_location (0% missing), requires_license (0% missing), calculated_host_listings_count (0% missing), scrape_id (0% missing), thumbnail_url (100% missing), medium_url (100% missing), xl_picture_url (100% missing), host_acceptance_rate (100% missing), instant_bookable (0% missing), neighbourhood_group_cleansed (100% missing), host_thumbnail_url (0,01% missing), host_picture_url (0,01% missing), jurisdiction_names (1% missing), experiences_offered (0% missing), , square_feet (98% missing), host_neighbourhood (14% missing), state (1% missing), host_location (0,3% missing), market (0,2% missing), host_has_profile_pic (0,01% missing), is_business_travel_ready (0% missing), has_availability (0% missing), last_scraped (0% missing)

# 4. Nettoyer + compléter + transformer les valeurs

In [4]:
#transformer en booléen les colonnes require_guest_phone_verification (0% missing), require_guest_profile_picture (0% missing), 

BOOL_COLS = ["require_guest_phone_verification", "require_guest_profile_picture", "host_is_superhost", "host_identity_verified"]
for col in BOOL_COLS:
    if col in df_listings.columns:
        df_listings[col] = (df_listings[col].astype(str).str.lower().isin(["t", "true", "1", "yes"]))

In [5]:
#convertir review_scores_rating sur 5
df_listings["review_scores_rating"] = (pd.to_numeric(df_listings["review_scores_rating"], errors="coerce") / 20).round(2)

In [6]:
#Nettoyer + transformer en float : price (0% missing), cleaning_fee (27% missing), security_deposit (31% missing),
#extra_people (0% missing), weekly_price (79% missing), monthly_price (87% missing)

PRICE_COLS = ["price", "cleaning_fee", "security_deposit", "extra_people", "weekly_price", "monthly_price"]
for col in PRICE_COLS:
    if col in df_listings.columns:
        df_listings[col] = (df_listings[col].astype(str).str.replace(r"[^0-9.]", "", regex=True))
        df_listings[col] = pd.to_numeric(df_listings[col], errors="coerce")
        df_listings[col] = df_listings[col].astype("float").fillna(0)

In [7]:
#créer et calculer la colonne "price_level" en mode quantiles basant sur colonne "price" : 1=petit <= q1 ; q1 < 2=moyen <= q2 ; 3=confort > q2

#regarder la distribution
df_listings["price"].describe(percentiles=[0.33, 0.66])

#calculer les seuils
q1 = df_listings["price"].quantile(0.33)
q2 = df_listings["price"].quantile(0.66)
q1, q2

#créer price_level
df_listings["price_level"] = np.nan

df_listings.loc[df_listings["price"] <= q1, "price_level"] = 1
df_listings.loc[(df_listings["price"] > q1) & (df_listings["price"] <= q2), "price_level"] = 2
df_listings.loc[df_listings["price"] > q2, "price_level"] = 3

df_listings[["price_level", "price"]].head(5)

,price_level,price
0,3.0,125.0
1,2.0,75.0
2,3.0,115.0
3,3.0,115.0
4,2.0,99.0


# 5. DataFrame Final (normer les colonnes afin de mapper avec les autres datasets dans streamlit)

19 colonnes normées UX streamlit : source_id, source, type, raw_type, url, lat, lon, name, address, postal_code, city, region, country, snippet, rating, review_count, price_level, max_people, distance_km

In [12]:
# Alléger le df --> Filtre qualité (garder seulement avec rating + min avis)
#df_listings = df_listings[df_listings["review_scores_rating"].notna() & (df_listings["number_of_reviews"] >= 3)]

# Alléger le df --> tronquer la colonne "description"
#df_listings["description_tron"] = (df_listings["description"].fillna("").astype(str).str.replace(r"\s+", " ", regex=True).str.strip().str.slice(0, 350))

# Garder uniquement les colonnes utiles
cols_keep = ["id", "listing_url", "name", "city", "zipcode", "state", "country", "summary",
             "latitude", "longitude", "review_scores_rating", "number_of_reviews", "accommodates", "price", "price_level"]

df_airbnb_clean = df_listings[cols_keep].copy()

# Créer les colonnes standards et les colonnes manquantes pour UX design
df_airbnb_clean["source"] = "AirBnb-Paris"
df_airbnb_clean["type"] = "Airbnb"
df_airbnb_clean["distance_km"] = np.nan
df_airbnb_clean["address"] = np.nan

# Normaliser / renommer
rename_map={"id": "source_id",
            "listing_url": "url",
            "latitude": "lat",
            "longitude": "lon",
            "zipcode": "postal_code",
            "state": "region",
            "review_scores_rating": "rating",
            "number_of_reviews": "review_count",
            "accommodates": "max_people",
            "summary" : "snippet"}
df_airbnb_clean_norm = df_airbnb_clean.rename(columns = rename_map, errors="ignore")

# réordonner les colonnes UX
UX_COLUMNS = ["source_id", "source", "type", "url", "lat", "lon",
              "name", "address", "postal_code", "city", "region", "country",
              "snippet", "rating", "review_count", "price_level", "max_people", "distance_km", "price"]

for col in UX_COLUMNS:
    if col not in df_airbnb_clean_norm.columns:
        df_airbnb_clean_norm[col] = None
        
df_airbnb_clean_normux = df_airbnb_clean_norm[UX_COLUMNS]

#sauvegarder les changements
df_airbnb_Paris = df_airbnb_clean_normux.copy()

# Export parquet final (un seul fichier)
df_airbnb_Paris.to_parquet("df_airbnb_Paris.parquet", index=False, engine="pyarrow", compression="zstd", compression_level=9)

#vérifier
display(df_airbnb_Paris.head(3))
display(df_airbnb_Paris.info())

,source_id,source,type,url,lat,lon,name,address,postal_code,city,region,country,snippet,rating,review_count,price_level,max_people,distance_km,price
0,2577,AirBnb-Paris,Airbnb,https://www.airbnb.com/rooms/2577,48.869933,2.362511,Loft for 4 by Canal Saint Martin,NaN,75010,Paris,Île-de-France,France,"100 m2 loft (1100 sq feet) with high ceiling, ...",NaN,0,3.0,4,NaN,125.0
1,3109,AirBnb-Paris,Airbnb,https://www.airbnb.com/rooms/3109,48.833494,2.318518,zen and calm,NaN,75014,Paris,Île-de-France,France,Appartement très calme de 50M2 Belle lumière D...,5.0,7,2.0,2,NaN,75.0
2,5396,AirBnb-Paris,Airbnb,https://www.airbnb.com/rooms/5396,48.851001,2.358690,Explore the heart of old Paris,NaN,75004,Paris,Ile-de-France,France,"Cozy, well-appointed and graciously designed s...",4.7,148,3.0,2,NaN,115.0


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59881 entries, 0 to 59880
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   source_id     59881 non-null  int64  
 1   source        59881 non-null  object 
 2   type          59881 non-null  object 
 3   url           59881 non-null  object 
 4   lat           59881 non-null  float64
 5   lon           59881 non-null  float64
 6   name          59807 non-null  object 
 7   address       0 non-null      float64
 8   postal_code   59084 non-null  object 
 9   city          59860 non-null  object 
 10  region        59151 non-null  object 
 11  country       59881 non-null  object 
 12  snippet       57524 non-null  object 
 13  rating        46289 non-null  float64
 14  review_count  59881 non-null  int64  
 15  price_level   59881 non-null  float64
 16  max_people    59881 non-null  int64  
 17  distance_km   0 non-null      float64
 18  price         59881 non-nu

None